### ISSUE TITLE
Top Level Menu not repeating pages on sub menus

### ISSUE THREAD

**Issue by marshalc** [ouh-churchill/quod#1]
When using wagtailmenus, and specifying that top level pages should also appear in their sub menus (so that they can actually be clicked on!), those pages are not appearing. 

In fact, the only thing appearing in the top navbar menu is exactly what is selected in the Main Menu choices, and their sub-pages only.

**Comment by marshalc** [comment]
Still an issue with the latest release of Wagtailmenus. Having to manually debug as it appears we're following the documented approach.

**Comment by marshalc** [comment]
Have removed wagtailmenus module as deemed non-functional, and implemented a simple solution based on the wagtail demosite codebase.

**Comment by marshalc** [comment]
(this was a frustrating 4 hours of bashing my head against wagtailmenus, and a much more straightforward 15 mins to get the workaround solution in place)

**Comment by tomdyson** [comment]
Was 'show in menus' turned on for those pages? It's off by default.

**Comment by marshalc** [comment]
Yup, show in menus was set, as was the other fields added by wagtailmenus (and I found evidence of that in the versioned data string for the page). In the end, not using that app has proven much more straightforward.
